#!/usr/bin/env bash

SCRIPTPATH="$( cd "$(dirname "$0")" || return ; pwd -P )"

#set background
if [ -f "$SCRIPTPATH/down.jpg" ] && [ -x "$(command -v feh)" ]; then
  feh --no-fehbg --bg-fill "$SCRIPTPATH"/down.jpg
fi

leftwm-command UnloadTheme || true

pkill -x -u "$(id -u)" compton 2>/dev/null || true
pkill -x -u "$(id -u)" picom 2>/dev/null || true
pkill -x -u "$(id -u)" polybar 2>/dev/null || true
"$SCRIPTPATH"/bin/eww-patched -c "$HOME"/.config/eww/eww-bar kill || true
pkill -x -u "$(id -u)" dunst 2>/dev/null || true
#pkill xss-lock
