#!/usr/bin/env bash

SCRIPTPATH="$( cd "$(dirname "$0")" || return ; pwd -P )"

#set background
if [ -f "$SCRIPTPATH/down.jpg" ] && [ -x "$(command -v feh)" ]; then
  feh --no-fehbg --bg-fill "$SCRIPTPATH"/down.jpg
fi

leftwm-command UnloadTheme || true

pkill compton || true
pkill picom || true
pkill polybar || true
"$SCRIPTPATH"/bin/eww-patched -c "$HOME"/.config/eww/eww-bar kill || true
pkill dunst || true
#pkill xss-lock
