#!/usr/bin/env bash

export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
export QT_QPA_PLATFORMTHEME="qt5ct"
autorandr -c

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s "$SCRIPTPATH"/down /tmp/leftwm-theme-down

# start eww daemon
eww daemon &


# Boot picom or compton if it exists
if [ -x "$(command -v picom)" ]; then
  picom --experimental-backends --config "$SCRIPTPATH"/picom/picom.conf &> /dev/null &
elif [ -x "$(command -v compton)" ]; then
  compton &> /dev/null &
fi

# Set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"

# Set background
if [ -x "$(command -v feh)" ]; then
  feh --no-fehbg --bg-fill "$SCRIPTPATH"/Background.png
fi

#Applications to 2run at startup
dunst -conf "$SCRIPTPATH"/dunst/dunstrc &
blueman-applet &



#open eww 'bar' windows
#this is a bit of an uggly hack, a more elegant way will hopefully be possible with a future `eww` version

ln -s  ~/.config/eww/eww-bar/* ~/.config/eww


sleep 1
index=0
sizes=( $(leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' ) )
for size in "${sizes[@]}"
do
    eww open bar$index
    eww -c $HOME/.config/eww/eww-bar
  let index=index+1
done

